name: shopping_app
description: "A new Flutter project."
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  get: ^4.7.3

  # HTTP client for making API requests
  http: ^1.6.0

  # Local storage for caching data
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1

  # UI enhancements
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Lato
      fonts:
      - asset: assets/fonts/Lato-Light.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
